# svtAv1GuiEx
# continuous integration settings

image: Visual Studio 2019

platform: Win32
configuration: Release
skip_non_tags: true

branches:
  only:
    - master

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 15
  - ps: Restart-Computer
  - ps: Start-Sleep -s 15
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - curl -o "nasminst.exe" https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-installer-x86.exe
  - start /wait nasminst.exe /S
  - set PATH=C:\Program Files (x86)\nasm;%PATH%
  - nasm --version
  
before_build:
  - ps: |
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
          $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if ([string]::IsNullOrEmpty($version))
      {
          $version = $env:APPVEYOR_BUILD_VERSION + '_Alpha'
      }
      $env:BUILD_VERSION=$version

  - echo %BUILD_VERSION%
  - appveyor UpdateBuild -Version "%BUILD_VERSION%"

build:
  parallel: true
  project: svtAV1guiEx.sln

after_build:
  - mkdir auo
  - copy Release\svtAV1guiEx.auo auo\svtAV1guiEx.auo
  - copy Release\svtAV1guiEx.ini auo\svtAV1guiEx.ini
  - 7z a -mx9 svtAV1guiEx_%BUILD_VERSION%.7z auo

artifacts:
  - path: svtAV1guiEx_%BUILD_VERSION%.7z
    name: svtAV1guiEx_%BUILD_VERSION%

deploy:
  provider: GitHub
  auth_token:
    secure: IDRwZWN1uQaTxb64SQnTDNJR5KPtCFPL3Mln9GrdZ7TSiyec/o1KXpOuh/50ZO5A
  artifact: svtAV1guiEx_%BUILD_VERSION%
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
